### ISSUE TITLE
Broken url path in font-face

### ISSUE THREAD

**Issue by Lukkian** [clean-css/clean-css#1200] opened 2022-01-31 23:44 UTC
### Environment

* jsDelivr using clean-css v5.2.2

### Input CSS [bootstrap-icons.css](https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css)

```css
@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2?e2f6e48459d8b0f394eea57aba940179") format("woff2"),
url("./fonts/bootstrap-icons.woff?e2f6e48459d8b0f394eea57aba940179") format("woff");
}
```

### Actual output CSS [bootstrap-icons.min.css](https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.min.css)

```css
@font-face{font-family:bootstrap-icons;src:url("../fonts/bootstrap-icons.woff2?e2f6e48459d8b0f394eea57aba940179") format("woff2"),url("../fonts/bootstrap-icons.woff?e2f6e48459d8b0f394eea57aba940179") format("woff")}
```

### Expected output CSS

```css
@font-face{font-family:bootstrap-icons;src:url("./fonts/bootstrap-icons.woff2?e2f6e48459d8b0f394eea57aba940179") format("woff2"),url("./fonts/bootstrap-icons.woff?e2f6e48459d8b0f394eea57aba940179") format("woff")}
```
This causes a 404 error in the .woff and woff2 font files.
This behavior does not occur in [clean-css v4.2.4](https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.min.css).

**Comment by jakubpawlowicz** [comment] 2022-02-01 09:26
Hey @Lukkian - clean-css 5.x changes rebasing behavior, see https://github.com/clean-css/clean-css#whats-new-in-version-50 - so you may need to play with `rebase` and `rebaseTo` flags.

**Comment by Lukkian** [comment] 2022-02-01 12:02
Is it possible to pass these flags to jsDelivr?

**Comment by jakubpawlowicz** [comment] 2022-02-01 12:13
Unfortunately, I am not familiar with jsDelivr at all.

**Comment by MartinKolarik** [comment] 2022-02-01 16:13
Hi, Martin from jsDelivr here. I asked a colleague to prepare a small code snippet to demonstrate the issue as I believe there may indeed be an issue related to rebasing when using multiple files input.

**Comment by jakubpawlowicz** [comment] 2022-02-01 16:21
Thanks @MartinKolarik, looking forward to the snippet.

**Comment by zarianec** [comment] 2022-02-01 18:18
Hey @jakubpawlowicz. After a small investigation, I managed to localize the issue with a jsDelivr and it looks like with a v5 release of clean-css it's no longer possible to get the behavior of v4.

```javascript
let minified = new CleanCSS({
    rebase: false,
    rebaseTo: '/npm/bootstrap-icons/fonts',
}).minify({
    '/npm/bootstrap-icons/fonts/bootstrap-icons.css': {
        styles: `@font-face{ src:url("./fonts/bootstrap-icons.woff2") format("woff2") }`,
    },
});

// v4 - @font-face tag was ignored: '@font-face{src:url(./fonts/bootstrap-icons.woff2) format("woff2")}'
// v5 - @font-face tag was rebaced: '@font-face{src:url(fonts/bootstrap-icons.woff2) format("woff2")}'
```

In v4 this combination of `rebase` and `rebaseTo` will apply the rebasing to `@import` tags in CSS and to a source map only.

But in v5 `rebase` option is completely ignored and will be set to `true` if `rebaseTo` is provided (L2 in a code):

https://github.com/clean-css/clean-css/blob/2854a27ef6c391f629ab9a3c8342daed2f49360d/lib/options/rebase.js#L1-L9

I'm not sure if this is expected behavior since changelog doesn't mention that it's not possible to explicitly set `rebase:false` if `rebaseTo` is set.

**Comment by jakubpawlowicz** [comment] 2022-02-02 09:53
Hey @Lukkian 

It's an expected behavior of v5 to treat all URLs equally. At this point I am not sure why 4.x treated them differently, whether it was intentional or a bug.

As of v5 the only way of doing what you want, would be to get rid of `rebase` and `rebaseTo` options, and write a plugin, which would deal with rebasing on its own, see https://github.com/clean-css/clean-css#plugins and https://github.com/clean-css/clean-css/blob/master/lib/optimizer/level-1/property-optimizers/ for plugin examples.

Hope this helps,
Jakub

**Comment by MartinKolarik** [comment] 2022-02-03 20:37
Thanks, @jakubpawlowicz, I believe the issue can be closed then.

**Comment by jakubpawlowicz** [comment] 2022-02-04 12:46
Cool, closing it now, please reopen if needed.

**Closed by jakubpawlowicz** 2022-02-04 12:46 UTC
Labels: more details needed
