### ISSUE TITLE
Source map paths issues

### ISSUE THREAD

**Issue by sprat** [clean-css/clean-css#688] opened 2015-10-09 11:41 UTC
I have a main css file which have a bunch of `@import` rules and I use this command to compile my css file:

```
cleancss --source-map --output dist/my.css css/my.css
```

However, in the source map file, the paths in the "sources" list are wrong: they start with "css/" instead of "../css/".

I think the source map paths should take into account the path to the output file.

**Comment by sprat** [comment] 2015-10-09 18:28
Note that, as a workaround, it works when I force the root path, but I get many "Both 'root' and output file given so rebasing URLs as absolute paths" warnings obviously...
```
cleancss --source-map --output dist/my.css --root dist/ css/my.css
```

**Comment by carltonf** [comment] 2015-10-17 11:49
Same issue here. 
But I've found adding --source-map-inline-sources also works around this issue, as the browser seems to read source from map directly if it's available there.

**Comment by sprat** [comment] 2015-11-03 12:31
Yes, it helps to workaround the issue, but the paths indicated in Firefox are still wrong

**Comment by jakubpawlowicz** [comment] 2015-11-03 13:12
@sprat even with `--source-map-inline-sources`? How's that in Chrome?

**Comment by sprat** [comment] 2015-11-03 13:45
Sorry, I've tried again and it seems that I was wrong: it's ok with ``--source-map-inline-sources``.

Anyway, I think I've spotted the problem in `clean.js`:
```
this.options = {
  // ...
  root: options.root || process.cwd(),
  // ...
};
```
I think `process.cwd()` is not enough, should probably be `process.cwd()` + the target `dirname`. Needs some testing tough.

**Comment by sprat** [comment] 2015-11-03 13:49
No, in fact, it's still wrong with `--source-map-inline-sources`, at least with Firefox's developer tools: the inlined sources are showing properly, but when we hover the inlined source filename, the path shown is wrong.

**Comment by jakubpawlowicz** [comment] 2015-11-03 17:35
Thanks for taking a look - let me recheck in Firefox & Chrome. I wonder if it's a specific or general issue.

**Comment by sprat** [comment] 2015-11-05 08:11
@jakubpawlowicz did you take the time to check? I am now convinced that we must use the target's directory instead of `process.cwd()` as root when no root is provided. This would behave the same as `process.cwd()` in most cases, but will work for filenames with directories. I must admit however that I don't understand why the code assigning the target is so complicated... Maybe I miss some use cases.

**Comment by jakubpawlowicz** [comment] 2017-01-25 20:59
Please recheck with recently released clean-css 4.0 and reopen this issue if the problem persists.

**Comment by zmoazeni** [comment] 2017-10-01 05:02
Yeah I can confirm this is still a problem. I put together a short example to show the problem: https://github.com/zmoazeni/clean-css-issue

The problem I see is that rebaseTo doesn't do anything with the "source" listed in the sourceMap whereas with v3 you could set the root. If you run that script against the two versions, you'll see that v3.4.2 doesn't include the "css/" portion of the source. And aside from using `cd`, you can't get around it with v4.1.9.

This is causing me issues with grunt-contrib-cssmin because you can't easily cd around.

**Comment by jakubpawlowicz** [comment] 2017-10-05 02:49
Hi @zmoazeni - thanks for the test case repo. I realize this is a step backward since 3.4 but it's all to make the clean-css internals less complex. I need to take a look whether `rebaseTo` could be used there or even using a hash input as a workaround - https://github.com/jakubpawlowicz/clean-css#how-to-work-with-source-maps

**Comment by jakubpawlowicz** [comment] 2022-03-30 11:18
Won't fix as clean-css is going into [maintenance mode](https://github.com/clean-css/clean-css/discussions/1209).

**Closed by jakubpawlowicz** 2022-03-30 11:18 UTC
Labels: more details needed
